### ISSUE TITLE
Support default options (`defaults:`)

### ISSUE THREAD

**Issue by dtruebin** [DrDynamic/dotbot-git#6]
As a user, I would like to be able to override the plugin's defaults, e.g., as follows:
```yaml
- defaults:
    git:
      method: clone
```

See [dotbot's readme section on this](https://github.com/anishathalye/dotbot/blob/v1.20.1/README.md#defaults).
